import os
import json
import re
import time
import requests
from openai import OpenAI
from dotenv import load_dotenv

# ── Load env ──────────────────────────────────────────────────────────────────
dotenv_path = os.path.join(os.path.dirname(__file__), '..', '.env.local')
load_dotenv(dotenv_path)

SUPABASE_URL         = os.getenv("NEXT_PUBLIC_SUPABASE_URL")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
NVIDIA_API_KEY       = os.getenv("NVIDIA_API_KEY2", "").strip()

# ── Config ────────────────────────────────────────────────────────────────────
AI_DELAY_S  = 2
OUTPUT_FILE = "cleaned_descriptions.json"
MODEL       = "deepseek-ai/deepseek-v3.2"

# ── NVIDIA client via OpenAI SDK ──────────────────────────────────────────────
nvidia_client = OpenAI(
    base_url = "https://integrate.api.nvidia.com/v1",
    api_key  = NVIDIA_API_KEY,
)

# ── Validate ──────────────────────────────────────────────────────────────────
missing = [k for k, v in {
    "NEXT_PUBLIC_SUPABASE_URL":  SUPABASE_URL,
    "SUPABASE_SERVICE_ROLE_KEY": SUPABASE_SERVICE_KEY,
    "NVIDIA_API_KEY":            NVIDIA_API_KEY,
}.items() if not v]

if missing:
    print(f"✗ Missing env vars: {', '.join(missing)}")
    exit(1)


# ══════════════════════════════════════════════════════════════════════════════
# DIRTY DETECTION — which descriptions have AI artifacts?
# ══════════════════════════════════════════════════════════════════════════════

ARTIFACT_PATTERNS = [
    r'\bStep\s+\d+\s*:',
    r'\bHere\s+is\s+the\s+(enriched|updated|new|cleaned)?\s*(product\s+)?description\b',
    r'\bHere\'?s\s+the\s+(enriched|updated|new|cleaned)?\s*(product\s+)?description\b',
    r'\bI\s+have\s+(enriched|updated|combined|woven|incorporated)\b',
    r'\bI\'ve\s+(enriched|updated|combined|woven|incorporated)\b',
    r'\bNote\s*:\s',
    r'\bIn\s+this\s+(description|version)\b',
    r'\bThe\s+task\s+is\s+to\b',
    r'\bAs\s+requested\b',
    r'\bAs\s+per\s+your\s+instructions\b',
]

def is_dirty(description: str) -> bool:
    if not description:
        return False
    for pattern in ARTIFACT_PATTERNS:
        if re.search(pattern, description, re.IGNORECASE | re.MULTILINE):
            return True
    return False


# ══════════════════════════════════════════════════════════════════════════════
# PROMPT — clean only, never rewrite
# ══════════════════════════════════════════════════════════════════════════════

def build_prompt(product_name: str, dirty: str) -> str:
    return f"""You are an editor. Your ONLY job is to remove AI-generated artifacts from a product description.

The description below was generated by an AI model and contains unwanted noise such as:
  - "Step 1:", "Step 2:" chain-of-thought reasoning
  - Preamble lines like "Here is the enriched description:" or "Here's the updated description:"
  - Commentary like "I have incorporated the colors..." or "I've woven in the material..."
  - "The task is to...", "As requested...", "Note:" annotations
  - Any text that is not the actual product description itself

YOUR RULES — read carefully:
  1. Extract the actual product description text and return it COMPLETELY UNCHANGED
  2. Do NOT rephrase, improve, rewrite, or add anything — not a single word
  3. Do NOT remove any sentence that is genuinely part of the description
  4. The output must be ONLY the clean description — nothing else
  5. If the description has no artifacts at all, return it exactly as-is

Product name: {product_name}

Dirty description:
\"\"\"
{dirty}
\"\"\"

Return a JSON object with one field: "description" containing only the cleaned text.
No other fields. No explanation. No preamble. Just the JSON.
"""


# ══════════════════════════════════════════════════════════════════════════════
# AI CALLER — DeepSeek V3.2 via NVIDIA, streaming, thinking mode
# ══════════════════════════════════════════════════════════════════════════════

def call_deepseek(prompt: str) -> str:
    """
    Streams the response. Collects only `content` chunks — ignores `reasoning_content`
    (the thinking tokens). Parses the final JSON and returns the description string.
    """
    stream = nvidia_client.chat.completions.create(
        model    = MODEL,
        messages = [{"role": "user", "content": prompt}],
        temperature = 0.1,   # very low — we want deterministic extraction, not creativity
        top_p       = 0.95,
        max_tokens  = 1024,
        extra_body  = {"chat_template_kwargs": {"thinking": True}},
        stream      = True,
    )

    content_parts = []

    for chunk in stream:
        if not getattr(chunk, "choices", None):
            continue
        delta = chunk.choices[0].delta

        # Skip reasoning/thinking tokens — we only want the final answer
        reasoning = getattr(delta, "reasoning_content", None)
        if reasoning:
            continue  # intentionally ignore

        if delta.content is not None:
            content_parts.append(delta.content)

    raw = "".join(content_parts).strip()

    if not raw:
        raise RuntimeError("Model returned empty content")

    # Strip markdown fences if model wrapped in ```json ... ```
    fence = re.search(r"```(?:json)?\n?([\s\S]*?)\n?```", raw)
    json_str = fence.group(1) if fence else raw

    parsed = json.loads(json_str.strip())
    result = parsed.get("description", "").strip()

    if not result:
        raise RuntimeError(f"JSON had no 'description' field. Raw: {raw[:200]}")

    return result


# ══════════════════════════════════════════════════════════════════════════════
# DATABASE
# ══════════════════════════════════════════════════════════════════════════════

def fetch_all_products():
    resp = requests.get(
        f"{SUPABASE_URL}/rest/v1/products",
        headers={
            "apikey":        SUPABASE_SERVICE_KEY,
            "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
        },
        params={
            "select":  "id,name,description",
            "deleted": "eq.false",
            "limit":   1000,
        }
    )
    if resp.status_code != 200:
        raise RuntimeError(f"Supabase fetch failed {resp.status_code}: {resp.text[:300]}")
    return resp.json()


# ══════════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════════

def main():
    print("╔══════════════════════════════════════════════╗")
    print("║   RP Apparels — Description Cleaner          ║")
    print("║   Model  : DeepSeek V3.2 via NVIDIA          ║")
    print("║   Output : cleaned_descriptions.json         ║")
    print("║   DB     : NOT touched — review JSON first   ║")
    print("╚══════════════════════════════════════════════╝\n")

    print("Fetching products...", end=" ", flush=True)
    products = fetch_all_products()
    print(f"{len(products)} found")

    dirty_products = [p for p in products if is_dirty(p.get("description") or "")]
    clean_products = [p for p in products if not is_dirty(p.get("description") or "")]

    print(f"\n  ✓ Already clean  : {len(clean_products)}")
    print(f"  ✗ Dirty (to fix) : {len(dirty_products)}")

    if not dirty_products:
        print("\n  Nothing to clean ✓")
        return

    print(f"\n  Dirty products:")
    for p in dirty_products:
        preview = (p.get("description") or "")[:70]
        print(f"    - \"{p['name']}\": {preview}...")

    print(f"\n  Processing {len(dirty_products)} products...\n")
    print("─" * 54)

    results = []
    success = 0
    failed  = 0

    for i, p in enumerate(dirty_products, start=1):
        name  = p["name"]
        dirty = p.get("description") or ""

        print(f"\n  [{i}/{len(dirty_products)}] \"{name}\"")
        print(f"    Before: \"{dirty[:80]}{'...' if len(dirty) > 80 else ''}\"")

        try:
            print(f"    → Cleaning... ", end="", flush=True)
            cleaned = call_deepseek(build_prompt(name, dirty))
            print("✓")
            print(f"    After:  \"{cleaned[:80]}{'...' if len(cleaned) > 80 else ''}\"")

            results.append({
                "id":     p["id"],
                "name":   name,
                "old":    dirty,
                "new":    cleaned,
                "model":  MODEL,
                "status": "ready",
            })
            success += 1

        except Exception as e:
            print(f"✗\n    Error: {e}")
            results.append({
                "id":     p["id"],
                "name":   name,
                "old":    dirty,
                "new":    None,
                "model":  MODEL,
                "status": "failed",
                "error":  str(e),
            })
            failed += 1

        if i < len(dirty_products):
            time.sleep(AI_DELAY_S)

    # ── Save JSON ─────────────────────────────────────────────────────────────
    output_path = os.path.join(os.path.dirname(__file__), OUTPUT_FILE)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    print(f"\n╔══════════════════════════════════════════════╗")
    print(f"║                   Summary                    ║")
    print(f"╠══════════════════════════════════════════════╣")
    print(f"║  Cleaned  : {str(success).ljust(33)}║")
    print(f"║  Failed   : {str(failed).ljust(33)}║")
    print(f"║  Saved to : {OUTPUT_FILE.ljust(33)}║")
    print(f"╚══════════════════════════════════════════════╝")
    print(f"\n  Review {OUTPUT_FILE}, then run push_descriptions.py to apply to Supabase.")


if __name__ == "__main__":
    main()